In [ ]:
import numpy as np

In [ ]:
# Creating a 1D array from a list
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
a[0]

np.int64(1)

In [ ]:
a[0] = a[0] + 1

In [ ]:
a

array([2, 2, 3])

In [ ]:
# Creating a 2D array from a list of lists
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
b[1]

array([3, 4])

In [ ]:
akshara = b[1]

In [ ]:
akshara

array([3, 4])

In [ ]:
akshara[1]

np.int64(4)

In [ ]:
b[1][1]

np.int64(4)

In [ ]:
print(b[1][1])

4


In [ ]:
# Creating a 3D array from a list of lists of lists
c = np.array([[[1, 2],
                 [3, 4]],
              [[5, 6],
                 [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
c[1]

array([[5, 6],
       [7, 8]])

In [ ]:
c[1][0]

array([5, 6])

In [ ]:
c[1][0][1]

np.int64(6)

In [ ]:
charlie = np.array([100, 200, 300])

In [ ]:
oliver = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])

In [ ]:
charlie

array([100, 200, 300])

In [ ]:
oliver

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [ ]:
charlie * oliver

array([[ 10.,  40.,  90.],
       [ 40., 100., 180.],
       [ 70., 160., 270.]])