In [2]:
import numpy as np

a = np.array([[[ 1,  2,  3], [22,  5,  6], [ 7,  8,  9]],
              [[11, 12, 10], [ 4, 14, 15], [16, 17, 18]],
              [[19, 20, 21], [13, 23, 24], [25, 26, 27]]])

In [4]:
a[1]

array([[11, 12, 10],
       [ 4, 14, 15],
       [16, 17, 18]])

In [5]:
a[1][0]

array([11, 12, 10])

In [6]:
a[2]

array([[19, 20, 21],
       [13, 23, 24],
       [25, 26, 27]])

In [7]:
a[2][2][2]

np.int64(27)

In [8]:
a

array([[[ 1,  2,  3],
        [22,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 10],
        [ 4, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [13, 23, 24],
        [25, 26, 27]]])

In [11]:
a[0][2]

array([[ 1,  2,  3],
       [22,  5,  6],
       [ 7,  8,  9]])

In [12]:
a[1][2][1]

np.int64(17)

In [13]:
import numpy as np
random_seed = 1729
np.random.seed(random_seed)
N = 40
x = np.random.rand(N)
y = np.random.rand(N)

In [15]:
points = zip(x,y)
cities = list(points)

In [16]:
itinerary = list(range(0,N))

In [17]:
lines = []

In [18]:
for j in range(0,len(itinerary) - 1):
  lines.append([cities[itinerary[j]],cities[itinerary[j + 1]]])

In [21]:
def genlines(cities,itinerary):
  lines = []
  for j in range(0,len(itinerary) - 1):
    lines.append([cities[itinerary[j]],cities[itinerary[j + 1]]])
  return(lines)

In [22]:
import math
def howfar(lines):
  distance = 0
  for j in range(0,len(lines)):
    distance += math.sqrt(abs(lines[j][1][0] - lines[j][0][0])**2 + \
    abs(lines[j][1][1] - lines[j][0][1])**2)
  return(distance)

In [23]:
totaldistance = howfar(genlines(cities,itinerary))
print(totaldistance)

16.808756356994223


In [24]:
import matplotlib.collections as mc
import matplotlib.pylab as pl
def plotitinerary(cities,itin,plottitle,thename):
  lc = mc.LineCollection(genlines(cities,itin), linewidths=2)
  fig, ax = pl.subplots()
  ax.add_collection(lc)
  ax.autoscale()
  ax.margins(0.1)
  pl.scatter(x, y)
  pl.title(plottitle)
  pl.xlabel('X Coordinate')
  pl.ylabel('Y Coordinate')
  pl.savefig(str(thename) + '.png')
  pl.close()

In [25]:
plotitinerary(cities,itinerary,'TSP - Random Itinerary','aidan')

In [26]:
point = [0.5,0.5]
j = 10
distance = math.sqrt((point[0] - cities[j][0])**2 + (point[1] - cities[j][1])**2)

In [32]:
def findnearest(cities,idx,nnitinerary):
  point = cities[idx]
  mindistance = float('inf')
  minidx = - 1
  for j in range(0,len(cities)):
    distance = math.sqrt((point[0] - cities[j][0])**2 + (point[1] - cities[j][1])**2)
    if distance < mindistance and distance > 0 and j not in nnitinerary:
      mindistance = distance
      minidx = j
  return(minidx)

In [33]:
nnitinerary = [0]

In [34]:
def donn(cities,N):
  nnitinerary = [0]
  for j in range(0,N - 1):
    next = findnearest(cities,nnitinerary[len(nnitinerary) - 1],nnitinerary)
    nnitinerary.append(next)
  return(nnitinerary)

In [35]:
plotitinerary(cities,donn(cities,N),'TSP - Nearest Neighbor','amishi')