In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
a[7]

np.int64(8)

In [4]:
a.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
b = a.reshape(2, 4)

In [7]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
c = a.reshape(2, 2, 2)

In [10]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
c[0]

array([[1, 2],
       [3, 4]])

In [13]:
c[1]

array([[5, 6],
       [7, 8]])

In [14]:
c[:,:,0]

array([[1, 3],
       [5, 7]])

In [15]:
c[::-1,:,0]

array([[5, 7],
       [1, 3]])

In [16]:
np.transpose(c[:,:,0])

array([[1, 5],
       [3, 7]])